version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: server
    container_name: server
    restart: "on-failure"

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: client
    depends_on:
      - server
    container_name: client
    environment:
      HOST: server
    restart: "on-failure"